// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planstreet.Infrastructure.Context;

namespace Planstreet.Infrastructure.Migrations
{
    [DbContext(typeof(PlanstreetContext))]
    [Migration("20200908073555_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Planstreet.ApplicationCore.Entities.DefaultFolder", b =>
                {
                    b.Property<int>("DefaultFolderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreationTime");

                    b.Property<int?>("Creator");

                    b.Property<string>("RemoteHost")
                        .HasMaxLength(50);

                    b.Property<byte?>("Status");

                    b.Property<int?>("Updater");

                    b.Property<DateTime?>("UpdationTime");

                    b.HasKey("DefaultFolderId");

                    b.ToTable("DefaultFolder");
                });
#pragma warning restore 612, 618
        }
    }
}
